sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose -f docker-compose-dev.yml up -d --build

script:
  - docker-compose -f docker-compose-dev.yml exec users python manage.py test
  - docker-compose -f docker-compose-dev.yml exec users flake8 project

after_script:
  - docker-compose -f docker-compose-dev.yml down