version: '3.7'

services:


  rateapp:
    build:
      context: ./services/rateapp
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@rateapp-db:5432/rateapp_prod  # nuevo
      - DATABASE_TEST_URL=postgres://postgres:postgres@rateapp-db:5432/rateapp_test  # nuevo
    depends_on:
      - rateapp-db


  rateapp-db:
    build:
      context: ./services/rateapp/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - rateapp
