version: '3.7'

services:

  rateapp:
    build:
      context: ./services/rateapp
      dockerfile: Dockerfile
    volumes:
      - './services/rateapp:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@rateapp-db:5432/rateapp_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@rateapp-db:5432/rateapp_test
    depends_on:
      - rateapp-db

  rateapp-db:
    build:
      context: ./services/rateapp/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - rateapp
